version: "3.8"

services:
  app:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=kocibar
      - DB_PASS=supersecret
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=kocibar
      - POSTGRES_PASSWORD=supersecret

  frontend:
    build: 
      context: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.next
    ports:
      - "3000:3000"
